apiVersion: csi.storage.k8s.io/v1alpha1
kind: CSIDriver
metadata:
  name: csi.nasplugin.com
spec:
  attachRequired: false
---
# This YAML defines all API objects to create RBAC roles for csi node plugin.
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-nasplugin
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: csi-nasplugin
  template:
    metadata:
      labels:
        app: csi-nasplugin
    spec:
      tolerations:
        - operator: Exists
      priorityClassName: system-node-critical
      serviceAccount: csi-nas-plugin
      hostNetwork: true
      hostPID: true
      containers:
        - name: driver-registrar
          image: registry.cn-hangzhou.aliyuncs.com/plugins/csi-node-driver-registrar:v1.1.0
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/csi.nasplugin.com /registration/csi.nasplugin.com-reg.sock"]
          args:
            - "--v=5"
            - "--csi-address=/var/lib/kubelet/plugins/csi.nasplugin.com/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/csi.nasplugin.com/csi.sock"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/kubelet/
            - name: registration-dir
              mountPath: /registration

        - name: csi-nasplugin
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: registry.cn-hangzhou.aliyuncs.com/plugins/csi-nasplugin:v1.14.3-41ea73db
          imagePullPolicy: IfNotPresent
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(NODE_ID)"
            - "--v=5"
            - "--driver=csi.nasplugin.csi.com"
          env:
            - name: CSI_ENDPOINT
              value: unix://var/lib/kubelet/plugins/csi.nasplugin.com/csi.sock
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/kubelet/
              mountPropagation: "Bidirectional"
            - mountPath: /var/log/
              name: host-log
            - name: etc
              mountPath: /host/etc
      volumes:
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet/
            type: Directory
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: DirectoryOrCreate
        - name: host-log
          hostPath:
            path: /var/log/
        - name: etc
          hostPath:
            path: /etc
